### ISSUE TITLE
Is this repo active?

### ISSUE THREAD

**Issue by Fdr3iZzz** [kmaxii/CanvasVideoTranscriber#1]
Hey, I was looking for a way to interact with openai whisper in java and saw your github. Sadly, there is no code yet. I wanted to ask if you still plan on commiting something.
Thank you, have a nice day

**Comment by kmaxii** [comment]
Oh what? I mussed have messed something up. Going to upload the code right away

**Comment by kmaxii** [comment]
The code has now been published.
